- name: Configure Load Balancers
  import_playbook: load-balancer.yml

- name: Configure Gluster Servers
  import_playbook: gluster.yml

- name: Configure Kubernetes Cluster
  import_playbook: kubernetes-cluster.yml

- name: Configure Heketi as dynamic Gluster provisioner
  import_playbook: heketi.yml

- name: Install Kubernetes Tools (Monitoring and Logging)
  import_playbook: kubernetes-tools.yml

- name: Install Discourse
  import_playbook: discourse-server.yml
