apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: datalab-api-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: datalab-api
    spec:
      containers:
        - name: datalab-api
          image: nerc/datalab-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: VAULT_APP_ROLE
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: vaultAppRole
            - name: VAULT_API
              value: http://vault-service:8200
          livenessProbe:
            httpGet:
              path: /status
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: datalab-api-service
spec:
  ports:
    - name: api
      port: 8000
      targetPort: 8000
  selector:
    app: datalab-api
  type: NodePort
